package com.taller.modiesel.controller;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller to provide CSRF token to clients
 * This token must be included in all state-changing requests (POST, PUT, DELETE)
 */
@RestController
@RequestMapping("/api/csrf")
public class CsrfTokenController {

    /**
     * Get CSRF token
     * The token is automatically generated by Spring Security and stored in a cookie
     * This endpoint allows clients to retrieve the token value
     */
    @GetMapping("/token")
    public CsrfToken csrfToken(CsrfToken token) {
        return token;
    }
}
